ALTER TABLE `#__deallab_customfields` ADD COLUMN `ordering` int(11) NOT NULL after `value`;
ALTER TABLE `#__deallab_deal_categories` ADD PRIMARY KEY(`deal_id`,`category_id`);
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `publish_up` `publish_up` datetime NOT NULL after `ordering`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `publish_down` `publish_down` datetime NOT NULL after `publish_up`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `cpn_valid_from` `cpn_valid_from` datetime NOT NULL after `publish_down`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `cpn_valid_till` `cpn_valid_till` datetime NOT NULL after `cpn_valid_from`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `checked_out` `checked_out` int(11) NOT NULL after `cpn_valid_till`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `checked_out_time` `checked_out_time` datetime NOT NULL after `checked_out`;
ALTER TABLE `#__deallab_deals` ADD COLUMN `shipping` text DEFAULT NULL after `price_type`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `merchant_title` `merchant_title` varchar(64) NOT NULL after `shipping`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `merchant_email` `merchant_email` varchar(64) NOT NULL after `merchant_title`;
ALTER TABLE `#__deallab_deals` ADD COLUMN `options` text NOT NULL after `merchant_email`;
ALTER TABLE `#__deallab_deals` CHANGE COLUMN `state` `state` tinyint(1) NOT NULL DEFAULT '0' after `options`;
ALTER TABLE `#__deallab_deals` DROP COLUMN `shipping_price`;
ALTER TABLE `#__deallab_deals` DROP COLUMN `params`;
ALTER TABLE `#__deallab_orders` ADD COLUMN `user_id` int(11) NOT NULL DEFAULT '0' after `address_id`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `email` `email` varchar(64) NOT NULL after `user_id`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `details` `details` text DEFAULT NULL after `email`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `notes` `notes` text DEFAULT NULL after `details`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `amount` `amount` double NOT NULL after `notes`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `currency` `currency` varchar(5) NOT NULL after `amount`;
ALTER TABLE `#__deallab_orders` ADD COLUMN `shipping` tinyint(1) NOT NULL DEFAULT '0' after `currency`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `status` `status` tinyint(1) NOT NULL DEFAULT '0' after `shipping`;
ALTER TABLE `#__deallab_orders` ADD COLUMN `gateway` varchar(64) NOT NULL after `status`;
ALTER TABLE `#__deallab_orders` CHANGE COLUMN `cdate` `cdate` datetime NOT NULL after `gateway`;
ALTER TABLE `#__deallab_orders` ADD COLUMN `mail_sent` tinyint(1) NOT NULL DEFAULT '0' after `gateway`;